#!/bin/bash
# auto-generated by scripts/config.py
unset CDPATH IFS LOCALE LD_LIBRARY_PATH LD_PRELOAD LD_AUDIT ORIGIN LC_ALL
PATH=/web/cs1511/19T2/private/scripts:/home/cs1511/bin:/web/cs1511/bin:/home/class/bin:/home/give/stable/bin:/usr/local/bin:/usr/bin:/bin/:/sbin:/usr/sbin:.
LANG=en_AU.utf8
LANGUAGE=en_AU:en
LC_COLLATE=POSIX
LC_NUMERIC=POSIX
private_directory=/web/cs1511/19T2/private
public_html_session_directory=/web/cs1511/19T2
base_directory=/web/cs1511/19T2
public_html_directory=/web/cs1511
scripts_directory=/web/cs1511/19T2/private/scripts
home_directory=/home/cs1511
bin_directory=/home/cs1511/bin
course_account=cs1511
course_code=COMP1511
course_code_lower_case=comp1511
course_code_regex=COMP1511
course_number=1511
postgraduate_course_code=''
course_name='Programming Fundamentals'
unsw_session=19T2
canonical_url='https://cgi.cse.unsw.edu.au/~cs1511/19T2/'
github_repo_url=https://github.com/COMP1511UNSW/course_materials
course_forum_url=https://piazza.com/class/jwekyxvlxn17k1
GIVEHOME=/home/give/stable
CLASS=COMP1511
GIVEPERIOD=19T2
lecture_recordings_url='https://moodle.telt.unsw.edu.au/course/view.php?id=37604'
WORK=/web/cs1511/19T2/work
OUT=/web/cs1511/19T2/work/.out
MARKED=/web/cs1511/19T2/work/.out/.marked
SMSDB=/web/cs1511/19T2/work/19T2db.sms
SMSDB_SQLITE_COPY=/web/cs1511/19T2/work/19T2db.sqlite3
extensions_database=/web/cs1511/19T2/work/extensions.sqlite3
testing_results_file=/web/cs1511/19T2/work/testing_results.json
enrollments_file=/web/cs1511/19T2/work/enrollments.json
unsw_ldap_password_file=/web/cs1511/.unsw_ldap_password
autotest_results_directory=/web/cs1511/19T2/work/autotest_results
autotest_upload_url='http://cgi.cse.unsw.edu.au/~cs1511/19T2/cgi/autotest_upload.cgi'
tutors_url='https://cgi.cse.unsw.edu.au/~cs1511/19T2/flask_tutors.cgi'
activities_url='https://cgi.cse.unsw.edu.au/~cs1511/19T2/activities/'
export PATH LANG LANGUAGE LC_COLLATE LC_NUMERIC WORK OUT MARKED SMSDB GIVEHOME GIVEPERIOD CLASS PATH
export ARCH=${ARCH:=pc.i86.linux}
